name: Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      some_input:
        description: 'An example input'
        required: false

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest # Runner size here doesn't significantly impact this job
    name: Dispatch Event
    steps:
      - name: Trigger target workflow
        env:
          # Ensure this secret contains a token with 'repo' scope for repository_dispatch
          WORKFLOW_DISPATCH_TOKEN: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
        run: |
          echo "Triggering build workflow in repository: ${{ github.repository }}"
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $WORKFLOW_DISPATCH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/json" \
            -d '{"event_type":"trigger-build", "client_payload": {"message": "Triggered from dispatch workflow", "input": "${{ github.event.inputs.some_input }}"}}' \
            https://api.github.com/repos/${{ github.repository }}/dispatches # Use dynamic repository variable
